//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Postman.WebApi.MsBuildTask {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Postman.WebApi.MsBuildTask.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load assembly {0}.
        /// </summary>
        public static string AssemblyLoadFailure {
            get {
                return ResourceManager.GetString("AssemblyLoadFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .config.
        /// </summary>
        public static string ConfigFileExtension {
            get {
                return ResourceManager.GetString("ConfigFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to url.
        /// </summary>
        public static string DefaultEnvironmentKey {
            get {
                return ResourceManager.GetString("DefaultEnvironmentKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/{controller}.
        /// </summary>
        public static string DefaultRouteTemplate {
            get {
                return ResourceManager.GetString("DefaultRouteTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .dll.
        /// </summary>
        public static string DllFileExtension {
            get {
                return ResourceManager.GetString("DllFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating Postman collection for {0}.
        /// </summary>
        public static string GeneratingPostmanCollection {
            get {
                return ResourceManager.GetString("GeneratingPostmanCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ApiController derived classes were found.
        /// </summary>
        public static string NoApiControllerClassesFound {
            get {
                return ResourceManager.GetString("NoApiControllerClassesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .postman.json.
        /// </summary>
        public static string OutputFileExtension {
            get {
                return ResourceManager.GetString("OutputFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postman collection file created at {0}.
        /// </summary>
        public static string PostmanCollectionCreated {
            get {
                return ResourceManager.GetString("PostmanCollectionCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The XML comments file for the target assembly does not exist.  Ensure that XML documentation output is enabled in the project properties..
        /// </summary>
        public static string XmlCommentsFileNotFound {
            get {
                return ResourceManager.GetString("XmlCommentsFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .xml.
        /// </summary>
        public static string XmlFileExtension {
            get {
                return ResourceManager.GetString("XmlFileExtension", resourceCulture);
            }
        }
    }
}
